import logging

import typer

from src import dataset
from src import model
from src.metrics import metrics_pretty_print
from src.drknn import RobustTextClassifier


dataset.VALIDATION_PART = 0.2
model.TEST_PART = 0.4

DEFAULT_DATA_PATH = "data/classification_dataset_rare_reasons_20_30"
DEFAULT_MODEL_PATH = "data/models/dr_knn_model.joblib"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("Dr.kNN model training and evaluation")


def main(
    data_path: str = DEFAULT_DATA_PATH,
    path_to_save: str = DEFAULT_MODEL_PATH,
):
    """
    Script for model training. To be ran after `preprocessing.py --min-samples 20 --max-samples 30`
    The script:
        1. Builds a dataset for training and validation from prepared dataset.
        2. Trains the ContactReasonPredictionModel on training data per contact reason.
        3. Evaluates the model on validation data per account.
        4. Saves the trained model.

    Parameters:
        - data_path (str) : path to dataset generated by `preprocessing.py` script
        - path_to_save (str) : path to save the trained model.
            [!] if changed the path in app.py should be updated.

    Returns:
        None

    How to run:
    > python main.py
    """
    tickets_dataset = dataset.TicketsDataset(data_path)
    contact_reason_model = model.ContactReasonPredictionModel(
        RobustTextClassifier, model_args=[2, 2], model_kwargs={"lr": 1e-1, "n_iter": 10}
    )
    aggregated_test_metrics, contact_reason_results = contact_reason_model.train(
        tickets_dataset, data_rate=1
    )
    logger.info(
        "Training results aggregated per contact_reason, binary classification:\n"
        + metrics_pretty_print(aggregated_test_metrics)
    )
    with open("results/dr_knn_training.log", "w") as training_log:
        print(metrics_pretty_print(aggregated_test_metrics), file=training_log)
        print(metrics_pretty_print(contact_reason_results), file=training_log)
    aggregated_val_metrics, account_results = contact_reason_model.validate(
        tickets_dataset
    )
    logger.info(
        "Validation results aggregated per acoount_id, multiclass classification:\n"
        + metrics_pretty_print(aggregated_val_metrics)
    )
    logger.info(
        "Validation results per account, multiclass classification:\n"
        + metrics_pretty_print(account_results)
    )
    with open("results/dr_knn_validation.log", "w") as validation_log:
        print(metrics_pretty_print(aggregated_val_metrics), file=validation_log)
        print(metrics_pretty_print(account_results), file=validation_log)

    if path_to_save:
        contact_reason_model.save(path_to_save)


if __name__ == "__main__":
    typer.run(main)
